[2022-01-27 16:59:40,774] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2022-01-27 16:59:40,786] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2022-01-27 16:59:40,786] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-27 16:59:40,786] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-27 16:59:40,786] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-27 16:59:40,805] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2021-01-02 06:00:00+00:00
[2022-01-27 16:59:40,813] {standard_task_runner.py:52} INFO - Started process 1411 to run task
[2022-01-27 16:59:40,818] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2021-01-02T06:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpkljjmf51', '--error-file', '/tmp/tmp4qmgmiay']
[2022-01-27 16:59:40,819] {standard_task_runner.py:77} INFO - Job 48: Subtask wget
[2022-01-27 16:59:40,896] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [running]> on host f18aba08ba75
[2022-01-27 16:59:40,969] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T06:00:00+00:00
[2022-01-27 16:59:40,970] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-27 16:59:40,971] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv -O /opt/***/output.csv']
[2022-01-27 16:59:40,985] {subprocess.py:85} INFO - Output:
[2022-01-27 16:59:40,989] {subprocess.py:89} INFO - bash: wget: command not found
[2022-01-27 16:59:40,990] {subprocess.py:93} INFO - Command exited with return code 127
[2022-01-27 16:59:41,012] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-01-27 16:59:41,025] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20210102T060000, start_date=20220127T165940, end_date=20220127T165941
[2022-01-27 16:59:41,043] {standard_task_runner.py:92} ERROR - Failed to execute job 48 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-01-27 16:59:41,069] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-27 16:59:41,127] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-27 19:26:52,845] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2022-01-27 19:26:52,863] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2022-01-27 19:26:52,863] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-27 19:26:52,863] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-27 19:26:52,863] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-27 19:26:52,879] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2021-01-02 06:00:00+00:00
[2022-01-27 19:26:52,886] {standard_task_runner.py:52} INFO - Started process 771 to run task
[2022-01-27 19:26:52,890] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2021-01-02T06:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp1661vc6f', '--error-file', '/tmp/tmpdl9e8jfp']
[2022-01-27 19:26:52,891] {standard_task_runner.py:77} INFO - Job 113: Subtask wget
[2022-01-27 19:26:52,974] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [running]> on host 9ee291f061ff
[2022-01-27 19:26:53,037] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-27 19:26:53,064] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T06:00:00+00:00
[2022-01-27 19:26:53,065] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-27 19:26:53,066] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/output_2021-01.csv']
[2022-01-27 19:26:53,088] {subprocess.py:85} INFO - Output:
[2022-01-27 19:27:03,810] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-27 19:27:03,856] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=wget, execution_date=20210102T060000, start_date=20220127T192652, end_date=20220127T192703
[2022-01-27 19:27:03,898] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-27 19:27:03,949] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
